name: Publish .NET Core Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Projede kullandığınız .NET Core versiyonunu belirtin

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    - name: Checkout another repository
      uses: actions/checkout@v2
      with:
        repository: orionmusa/TestPublish  # Hedef repo
        token: ${{ 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 }} # Diğer repo için erişim tokenı
        path: publish-repo

    - name: Copy publish files
      run: cp -r ./publish/* ./publish-repo/

    - name: Push publish files to another repository
      run: |
        cd publish-repo
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Publishing project"
        git push
